import type { ReactNode } from "react";
import { AlertCircle, ArrowLeft, ChevronRight, Database, Inbox, LoaderCircle, RefreshCw } from "lucide-react";
export const formatDate=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"-";
export const formatNumber=(value:number)=>new Intl.NumberFormat("zh-CN").format(value);
export const labelOf=(value:string)=>({approved:"已批准",draft:"草案",superseded:"已被替代",direct_competitor:"直接竞争对手",alternative:"替代方案",reference:"参考实体",excluded:"已排除",succeeded:"成功",completed:"已完成",failed:"失败",partial:"部分完成",included:"已纳入",authorized:"已授权",not_authorized:"未关联执行授权",terminal_failure:"终止失败",retryable_failure:"可重试失败",budget_stopped:"预算停止",pending:"待处理",api:"官方 API",deepseek:"DeepSeek",baseline:"固定基准",exploration:"轮换探索",trigger:"触发问题",neutral_category:"中性品类",brand_direct:"品牌直问",competitor_direct:"竞品直问",brand_vs_competitor:"品牌对比",inspiration:"灵感发现",comparison:"对比选择",planning:"行程规划",booking:"预订决策",risk_confirmation:"风险确认",network_error:"网络连接失败",incomplete_response:"回答不完整"}[value]??value.replaceAll("_"," "));
export function PageHeader({eyebrow,title,description,back,onBack,actions}: {eyebrow:string;title:string;description:string;back?:string;onBack?:()=>void;actions?:ReactNode}) {return <header className="page-header"><div>{onBack?<button className="back-link" onClick={onBack}><ArrowLeft/> {back??"返回"}</button>:null}<p className="page-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{actions?<div className="page-actions">{actions}</div>:null}</header>}
export function Status({value,tone}:{value:string;tone?:"good"|"warn"|"bad"|"neutral"}) {const inferred=tone??(value==="succeeded"||value==="approved"?"good":value.includes("failure")?"bad":"neutral");return <span className={`status status--${inferred}`}>{labelOf(value)}</span>}
export function Metric({label,value,note}:{label:string;value:ReactNode;note:string}) {return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
export function Loading({label="正在读取真实数据"}:{label?:string}) {return <div className="state"><LoaderCircle className="spin"/><strong>{label}</strong><span>页面不会显示旧租户或模拟数据。</span></div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}) {return <div className="state state--error"><AlertCircle/><strong>暂时无法显示</strong><span>{message}</span>{retry?<button className="button button--secondary" onClick={retry}><RefreshCw/>重试</button>:null}</div>}
export function Empty({title,description}:{title:string;description:string}) {return <div className="state"><Inbox/><strong>{title}</strong><span>{description}</span></div>}
export function TableLink({children,onClick}:{children:ReactNode;onClick:()=>void}) {return <button className="table-link" onClick={onClick}>{children}<ChevronRight/></button>}
export function ContextBar({children}:{children:ReactNode}) {return <section className="context-bar"><Database/><div>{children}</div></section>}
