import {createHash,randomUUID} from "node:crypto";
import {z} from "zod";
import {gapRoutingSnapshotSchema,type GapRoutingSnapshot} from "../evidence-gap-routing/evidence-gap-routing.js";

export const actionPackageStatusSchema=z.enum(["waiting_facts","ai_can_prepare","waiting_yes_no","no_action"]);
export const actionPackageSchema=z.object({id:z.string().uuid(),tenantId:z.string().uuid(),planId:z.string().uuid(),key:z.enum(["license_evidence","refund_policy","website_product_facts","product_service_detail"]),title:z.string().min(1),factLevel:z.literal("F4"),priority:z.number().int().positive(),status:actionPackageStatusSchema,risk:z.enum(["low","medium","high"]),sourceClusterIds:z.array(z.string().uuid()).min(1),sourceFindingIds:z.array(z.string().uuid()).min(1),businessGoal:z.string().min(1),aiPreparation:z.array(z.string().min(1)).min(1),humanInputs:z.array(z.string().min(1)),approvalQuestion:z.string().nullable(),afterHumanInput:z.string().min(1),dependencies:z.array(z.string().min(1)),acceptanceCriteria:z.array(z.string().min(1)).min(1),noActionOption:z.string().min(1),expectedWindow:z.string().min(1)});
export const optimizationActionPlanSchema=z.object({id:z.string().uuid(),tenantId:z.string().uuid(),rulesVersion:z.literal("optimization-action-plan.v1"),sourceRoutingSnapshotId:z.string().uuid(),inputSha256:z.string().regex(/^[a-f0-9]{64}$/),status:z.literal("completed"),sourceFindingCount:z.number().int().nonnegative(),sourceClusterCount:z.number().int().nonnegative(),packageCount:z.number().int().min(0).max(5),packages:z.array(actionPackageSchema).max(5),executionOrder:z.array(z.string().uuid()).max(5),createdAt:z.string().datetime({offset:true})});
export type OptimizationActionPlan=z.infer<typeof optimizationActionPlanSchema>;

type PackageDefinition={key:z.infer<typeof actionPackageSchema>["key"];themes:string[];title:string;status:z.infer<typeof actionPackageStatusSchema>;risk:"low"|"medium"|"high";businessGoal:string;aiPreparation:string[];humanInputs:string[];approvalQuestion:string|null;afterHumanInput:string;dependencies:string[];acceptanceCriteria:string[];noActionOption:string;expectedWindow:string};
const definitions:PackageDefinition[]=[
 {key:"license_evidence",themes:["license_trust","pure_play_assurance"],title:"资质与可信证据建设",status:"ai_can_prepare",risk:"high",businessGoal:"让游客和 AI 能从可核验页面确认经营主体、许可证及证据边界。",aiPreparation:["整理现有工商、许可证、欣欣认证和官网主体证据的引用清单","标出官方事实、平台认证与品牌自述的不同权重","草拟官网资质事实区字段和外部信源建设顺序"],humanInputs:[],approvalQuestion:"是否允许下一切片基于现有证据草拟资质事实区页面蓝图？",afterHumanInput:"经 Yes/No 后才能进入页面蓝图，不会直接修改官网或发布。",dependencies:[],acceptanceCriteria:["每项资质陈述能回溯到具体来源","商业认证与官方资质不混同","不存在5A、经营年限或团队规模的无证据扩写"],noActionOption:"保持现状并继续监测，但 AI 对品牌资质仍可能返回证据不足。",expectedWindow:"AI准备1天；外部信源建设2-6周"},
 {key:"refund_policy",themes:["refund_cancellation"],title:"退款、取消与履约政策确认",status:"waiting_facts",risk:"high",businessGoal:"把游客最关心的取消损失和办理时限建立为真实可执行政策。",aiPreparation:["提供结构化政策采集模板","在收到真实条款后检查时间点、费用、例外和办理流程是否完整","生成内部核对清单，防止公开表达超出合同"],humanInputs:["现行合同或退款规则","不同取消时间点的退款比例与已发生费用","退款办理时限、例外情况和责任人"],approvalQuestion:null,afterHumanInput:"AI 只会先生成待审核政策摘要；公开前仍需 Yes/No。",dependencies:["必须来自现行合同或实际执行政策，不能依据行业惯例推断"],acceptanceCriteria:["退款比例和时间点有明确依据","已发生费用和例外情形被说明","公开文本与合同一致并保留版本日期"],noActionOption:"不公开具体退款承诺，仅提示以签署合同为准；该证据缺口会继续保留。",expectedWindow:"资料齐全后1-2天整理；业务确认1-2周"},
 {key:"website_product_facts",themes:["pricing_offer","itinerary_service"],title:"官网价格与行程事实区",status:"waiting_facts",risk:"medium",businessGoal:"让价格、包含项和每日行程以带日期、可抓取的结构呈现。",aiPreparation:["基于现有2280-2480元和5天4晚事实草拟页面字段结构","设计价格有效期、费用包含/不含、每日行程、餐住车导和更新时间字段","准备 FAQ 与结构化数据蓝图，但不写营销正文"],humanInputs:["当前价格有效期、儿童价、单房差和旺季浮动规则","当前有效行程版本及每日时间线","餐食、住宿、车辆、导游标准和最后更新时间"],approvalQuestion:null,afterHumanInput:"AI 形成页面蓝图供 Yes/No；批准后才进入官网改造切片。",dependencies:["价格和行程必须由品牌确认当前有效版本","官网修改权限尚未授权"],acceptanceCriteria:["每个价格均显示适用条件与有效期","每日行程和服务包含项可被机器读取","页面不引用无法核验的销量、满意度或资质宣传"],noActionOption:"保留现有官网，但价格新鲜度与行程可发现性缺口继续存在。",expectedWindow:"资料齐全后1-3天形成蓝图"},
 {key:"product_service_detail",themes:["family_suitability","customization","product_portfolio","small_group_experience"],title:"产品服务颗粒度补充",status:"waiting_facts",risk:"medium",businessGoal:"一次补齐家庭适配、定制边界、其他线路和12人团体验，减少重复追问。",aiPreparation:["把四类缺口合并为一张产品事实表","对输入执行冲突、公开范围和禁用表达检查","仅从确认事实生成适用/不适用边界"],humanInputs:["老人儿童的步行、早起、台阶、健康和座位限制","可调整项目、确认时限、成团人数与加价规则","除5天4晚外的真实在售线路清单","12人团车辆、导游、接送、等待、餐住标准"],approvalQuestion:null,afterHumanInput:"AI 生成品牌真相增补草案；只有逐项确认后才成为可公开事实。",dependencies:["只能使用真实在售和真实履约能力","不以社保人数直接推断全部服务能力"],acceptanceCriteria:["四类信息只向用户询问一次","适用与不适用人群边界明确","未核验线路和服务能力不会进入公开事实"],noActionOption:"继续只使用已核验的单款5天4晚产品，不扩写产品矩阵或服务能力。",expectedWindow:"资料齐全后1-3天形成增补草案"},
];

export function createOptimizationActionPlan(tenantId:string,rawRouting:GapRoutingSnapshot,createdAt=new Date().toISOString()):OptimizationActionPlan{
 const routing=gapRoutingSnapshotSchema.parse(rawRouting);if(routing.tenantId!==tenantId)throw new Error("Routing snapshot tenant mismatch.");
 const planId=randomUUID();const packages=definitions.map((d,index)=>{const clusters=routing.clusters.filter(c=>d.themes.includes(c.theme));if(!clusters.length)return null;return actionPackageSchema.parse({id:randomUUID(),tenantId,planId,key:d.key,title:d.title,factLevel:"F4",priority:index+1,status:d.status,risk:d.risk,sourceClusterIds:clusters.map(c=>c.id),sourceFindingIds:[...new Set(clusters.flatMap(c=>c.findingIds))],businessGoal:d.businessGoal,aiPreparation:d.aiPreparation,humanInputs:d.humanInputs,approvalQuestion:d.approvalQuestion,afterHumanInput:d.afterHumanInput,dependencies:d.dependencies,acceptanceCriteria:d.acceptanceCriteria,noActionOption:d.noActionOption,expectedWindow:d.expectedWindow});}).filter((x):x is z.infer<typeof actionPackageSchema>=>x!==null);
 const covered=new Set(packages.flatMap(x=>x.sourceClusterIds));const uncovered=routing.clusters.filter(x=>!covered.has(x.id));if(uncovered.length)throw new Error(`Unroutable evidence gap themes: ${uncovered.map(x=>x.theme).join(",")}`);
 const inputSha256=createHash("sha256").update(JSON.stringify({routingId:routing.id,rulesVersion:routing.rulesVersion,inputSha256:routing.inputSha256,clusters:routing.clusters.map(c=>({id:c.id,theme:c.theme,score:c.priorityScore,findings:[...c.findingIds].sort()}))})).digest("hex");
 return optimizationActionPlanSchema.parse({id:planId,tenantId,rulesVersion:"optimization-action-plan.v1",sourceRoutingSnapshotId:routing.id,inputSha256,status:"completed",sourceFindingCount:routing.sourceFindingCount,sourceClusterCount:routing.clusterCount,packageCount:packages.length,packages,executionOrder:packages.map(x=>x.id),createdAt});
}
