import { aiVisibilitySchema, sourceAnalysisSchema } from "../../contracts/product-read";
import { Eye, FileSearch, Link2, MessageSquareText, ShieldCheck, TriangleAlert } from "lucide-react";
import { ContextBar, Empty, ErrorState, labelOf, Loading, Metric, PageHeader, Status, TableLink, formatDate } from "./components/ProductUi";
import { useApi } from "./hooks/useApi";

const visibilityState=(item:{plannedSamples:number;effectiveAnswers:number;failedSamples:number;analyzedAnswers:number})=>item.plannedSamples===0?{label:"尚未采集",tone:"neutral" as const}:item.effectiveAnswers===0&&item.failedSamples>0?{label:"采集失败",tone:"bad" as const}:item.effectiveAnswers===0?{label:"等待采集",tone:"neutral" as const}:item.analyzedAnswers===0?{label:"等待分析",tone:"warn" as const}:item.analyzedAnswers<item.effectiveAnswers?{label:"部分分析",tone:"warn" as const}:{label:"可核对",tone:"good" as const};
type VisibilityItem=ReturnType<typeof aiVisibilitySchema.parse>["items"][number];
type SourceItem=ReturnType<typeof sourceAnalysisSchema.parse>["items"][number];

function VisibilityCard({item,onOpen}:{item:VisibilityItem;onOpen:()=>void}){const state=visibilityState(item);return <article className="analysis-mobile-card"><header><div><strong>{item.text}</strong><small>{labelOf(item.objectType)} · {labelOf(item.journeyStage)}</small></div><Status value={state.label} tone={state.tone}/></header><dl><div><dt>样本</dt><dd>{item.effectiveAnswers} 有效 · {item.failedSamples} 失败<small>{item.analyzedAnswers} 已分析 / {item.plannedSamples} 计划</small></dd></div><div><dt>品牌出现</dt><dd>{item.analyzedAnswers?`${item.mentionedAnswers} / ${item.analyzedAnswers} 条回答`:"未分析"}<small>{item.certainMentions} 处明确提及</small></dd></div><div><dt>品牌主张</dt><dd>{item.claimCount} 条<small>{item.positiveClaims} 正向 · {item.negativeClaims} 负向</small></dd></div><div><dt>适用排名</dt><dd>{item.applicableRanks.length?item.applicableRanks.join("、"):"不适用"}</dd></div></dl><button onClick={onOpen}>查看这个游客提问的回答与证据</button></article>}
function SourceCard({item,onOpen}:{item:SourceItem;onOpen:()=>void}){return <article className="analysis-mobile-card"><header><div><strong>{item.text}</strong><small>{labelOf(item.objectType)} · {labelOf(item.journeyStage)}</small></div></header><dl><div><dt>回答与扫描</dt><dd>{item.scannedAnswers} / {item.effectiveAnswers} 已扫描<small>{item.failedSamples} 个失败样本</small></dd></div><div><dt>链接候选</dt><dd>{item.inlineLinks} 正文链接<small>{item.sourceListItems} 来源项 · {item.absorptionCandidates} 吸收候选</small></dd></div><div><dt>结构化引用</dt><dd>{item.structuredCitations?`${item.structuredCitations} 条`:"尚无"}</dd></div><div><dt>页面取证</dt><dd>{item.successfulSnapshots} 成功<small>{item.blockedSnapshots} 受阻 · {item.failedSnapshots} 失败</small></dd></div></dl><button onClick={onOpen}>查看这个游客提问的回答与信源</button></article>}

export function AiVisibilityPage({navigate}:{navigate:(to:string)=>void}){
  const {data,error,retry}=useApi("/api/v1/ai-visibility",aiVisibilitySchema);
  if(error)return <><PageHeader eyebrow="数据分析" title="AI 可见性" description="逐个游客提问核对品牌是否出现、如何被描述。"/><ErrorState message={error} retry={retry}/></>;
  if(!data)return <Loading/>;
  const mentioned=data.items.filter(item=>item.mentionedAnswers>0).length;
  const analyzed=data.items.filter(item=>item.analyzedAnswers>0).length;
  return <><PageHeader eyebrow="数据分析" title="AI 可见性" description="不做脱离问题和样本的品牌总分；从每个游客提问看真实回答。"/>
    {data.context?<ContextBar><strong>当前分析口径</strong><span>问题组 V{data.context.panelVersion}</span><span>{labelOf(data.context.provider??"未记录")} · {data.context.model??"模型未记录"}</span><span>{data.context.rulesVersion??"规则未记录"}</span></ContextBar>:null}
    <section className="metric-grid analysis-summary"><Metric label="监测品牌" value={data.brand?.name??"未设定"} note="来自已批准实体集"/><Metric label="游客提问" value={data.items.length} note="当前批准问题组"/><Metric label="已具备分析" value={analyzed} note="至少一条回答已分析"/><Metric label="品牌曾出现" value={mentioned} note="按问题计数，不是市场份额"/></section>
    {!data.items.length?<Empty title="尚无游客提问" description="需要先批准游客问题组。"/>:<><section className="table-panel analysis-desktop-table"><div className="section-head"><div><h2>品牌在每个游客提问中的表现</h2><p>出现回答数的分母是已完成 GEO 分析的有效回答。</p></div></div><div className="table-scroll"><table><thead><tr><th>游客提问</th><th>样本</th><th>品牌出现</th><th>品牌主张</th><th>适用排名</th><th>状态</th></tr></thead><tbody>{data.items.map(item=>{const state=visibilityState(item);return <tr key={item.id}><td><TableLink onClick={()=>navigate(`/monitoring/insights/${item.id}`)}><span><strong>{item.text}</strong><small>{labelOf(item.objectType)} · {labelOf(item.journeyStage)}</small></span></TableLink></td><td><strong>{item.effectiveAnswers} 有效 · {item.failedSamples} 失败</strong><small>{item.analyzedAnswers} 条已分析 / {item.plannedSamples} 计划</small></td><td>{item.analyzedAnswers?<><strong>{item.mentionedAnswers} / {item.analyzedAnswers} 条回答</strong><small>{item.certainMentions} 处明确提及</small></>:<span className="evidence-missing">未分析</span>}</td><td><strong>{item.claimCount} 条</strong><small>{item.positiveClaims} 正向 · {item.negativeClaims} 负向</small></td><td>{item.applicableRanks.length?item.applicableRanks.join("、"):"不适用"}</td><td><Status value={state.label} tone={state.tone}/></td></tr>})}</tbody></table></div></section><section className="analysis-mobile-cards">{data.items.map(item=><VisibilityCard key={item.id} item={item} onOpen={()=>navigate(`/monitoring/insights/${item.id}`)}/>)}</section></>}
    <div className="notice"><TriangleAlert/><div><strong>如何理解“没有出现”</strong><p>只有已成功采集且已完成 GEO 分析的回答才可以判断品牌是否出现；失败和未分析样本不算品牌缺席。</p></div></div>
  </>;
}

export function SourceAnalysisPage({navigate}:{navigate:(to:string)=>void}){
  const {data,error,retry}=useApi("/api/v1/source-analysis",sourceAnalysisSchema);
  if(error)return <><PageHeader eyebrow="数据分析" title="引用与来源" description="从游客提问查看回答中的链接候选、引用与页面快照。"/><ErrorState message={error} retry={retry}/></>;
  if(!data)return <Loading/>;
  const structured=data.items.reduce((n,item)=>n+item.structuredCitations,0),snapshots=data.items.reduce((n,item)=>n+item.successfulSnapshots,0),blocked=data.items.reduce((n,item)=>n+item.blockedSnapshots+item.failedSnapshots,0);
  return <><PageHeader eyebrow="数据分析" title="引用与来源" description="链接候选、平台引用、来源项与页面取证分开表达。"/>
    {data.context?<ContextBar><strong>当前分析口径</strong><span>问题组 V{data.context.panelVersion}</span><span>{data.context.effectiveSamples} 有效 · {data.context.failedSamples} 失败</span><span>{data.context.rulesVersion??"规则未记录"}</span></ContextBar>:null}
    <section className="metric-grid analysis-summary"><Metric label="游客提问" value={data.items.length} note="当前批准问题组"/><Metric label="来源证据" value={data.evidence.length} note="链接与来源事件"/><Metric label="结构化引用" value={structured} note="由 AI 平台明确提供"/><Metric label="页面快照" value={snapshots} note={`${blocked} 个受阻或失败`}/></section>
    {!data.items.length?<Empty title="尚无游客提问" description="需要先批准游客问题组。"/>:<><section className="table-panel analysis-desktop-table"><div className="section-head"><div><h2>每个游客提问的信源证据</h2><p>“正文链接”和“来源项”只是候选，不等于平台明确引用。</p></div></div><div className="table-scroll"><table><thead><tr><th>游客提问</th><th>回答与扫描</th><th>链接候选</th><th>结构化引用</th><th>页面取证</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><TableLink onClick={()=>navigate(`/monitoring/insights/${item.id}`)}><span><strong>{item.text}</strong><small>{labelOf(item.objectType)} · {labelOf(item.journeyStage)}</small></span></TableLink></td><td><strong>{item.scannedAnswers} / {item.effectiveAnswers} 条已扫描</strong><small>{item.failedSamples} 个失败样本</small></td><td><strong>{item.inlineLinks} 正文链接 · {item.sourceListItems} 来源项</strong><small>{item.absorptionCandidates} 条内容吸收候选</small></td><td>{item.structuredCitations?`${item.structuredCitations} 条`:"尚无"}</td><td><strong>{item.successfulSnapshots} 成功</strong><small>{item.blockedSnapshots} 受阻 · {item.failedSnapshots} 失败</small></td></tr>)}</tbody></table></div></section><section className="analysis-mobile-cards">{data.items.map(item=><SourceCard key={item.id} item={item} onOpen={()=>navigate(`/monitoring/insights/${item.id}`)}/>)}</section></>}
    <section className="panel source-evidence-list"><div className="compact-head"><div><h2>来源证据明细</h2><p>每条记录保留所属游客提问、原始回答和最新页面快照。</p></div></div>{data.evidence.length?<div>{data.evidence.map(item=><article key={item.id}><div className="source-evidence-icon">{item.kind==="provider_citation"?<ShieldCheck/>:<Link2/>}</div><div><strong>{item.snapshot?.title??item.domain??labelOf(item.kind)}</strong><p>{item.question}</p><small>{labelOf(item.kind)} · {item.domain??"无可验证域名"} · {item.snapshot?`${labelOf(item.snapshot.status)} ${formatDate(item.snapshot.capturedAt)}`:"尚无页面快照"}</small></div><button className="text-action" onClick={()=>navigate(`/evidence/answers/${item.answerId}`)}>查看原始回答</button></article>)}</div>:<div className="inline-empty">当前真实回答未发现链接或来源项，不生成演示信源。</div>}</section>
    <section className="question-analysis-rules"><div><MessageSquareText/><span><strong>从游客提问开始</strong><small>不脱离问题类型聚合信源。</small></span></div><div><Link2/><span><strong>链接只是候选</strong><small>正文 URL 不自动升级为引用。</small></span></div><div><FileSearch/><span><strong>快照是取证结果</strong><small>成功、受阻和失败分开保留。</small></span></div><div><Eye/><span><strong>可回到原始回答</strong><small>不把聚合数当作独立事实。</small></span></div></section>
  </>;
}
