import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ArrowRight, Building2, Clock3, LockKeyhole, LogIn, ShieldX } from "lucide-react";
import { authSessionSchema, workspaceListSchema, type AuthSession, type WorkspaceMembership } from "../../contracts/auth";
import { getJson, postJson } from "./api";

function AccessFrame({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:ReactNode}){return <main className="access-page"><section className="access-brand"><div className="access-logo"><span>A</span> AnswerTravel</div><p>GEO 监测与决策平台</p><h1>从游客真实提问出发，持续看清 AI 如何认识你的品牌。</h1><ul><li>监测游客关心的问题</li><li>保留回答、信源与竞对证据</li><li>据此决定内容方向并同口径复测</li></ul></section><section className="access-panel"><div className="access-form"><p className="page-eyebrow">{eyebrow}</p><h2>{title}</h2><p className="access-description">{description}</p>{children}</div><footer>仅限受邀成员 · 无公开注册</footer></section></main>}
export function LoginPage({expired,onLogin}:{expired:boolean;onLogin:(session:AuthSession)=>void}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError(null);try{onLogin(await postJson("/api/v1/auth/login",{email,password},authSessionSchema));}catch(reason){setError(reason instanceof Error?reason.message:"暂时无法登录，请稍后重试。");}finally{setBusy(false)}};return <AccessFrame eyebrow={expired?"会话已失效":"成员登录"} title={expired?"请重新登录":"进入品牌空间"} description={expired?"为保护客户数据，本次会话已结束。重新登录后会返回刚才的页面。":"使用平台管理员通过安全渠道交付的受邀账号。"}>{expired?<div className="access-alert"><Clock3/><span>会话过期后不会继续显示上一品牌的数据。</span></div>:null}<form onSubmit={submit} className="login-form"><label>工作邮箱<input type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@company.com" required autoFocus/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="请输入密码" required/></label>{error?<p className="form-error" role="alert">{error}</p>:null}<button className="button button--primary access-submit" disabled={busy}>{busy?"正在验证":"登录"}<LogIn/></button></form><p className="access-help"><LockKeyhole/>忘记密码请联系平台管理员进行受审计重置。</p></AccessFrame>}
export function WorkspaceSelectionPage({onSelected}:{onSelected:(session:AuthSession)=>void}){const[items,setItems]=useState<WorkspaceMembership[]|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);useEffect(()=>{void getJson("/api/v1/workspaces",workspaceListSchema).then(value=>setItems(value.items)).catch(reason=>setError(reason instanceof Error?reason.message:"无法读取品牌空间。"));},[]);if(error)return <NoPermissionPage detail={error}/>;return <AccessFrame eyebrow="品牌空间" title="选择本次要查看的品牌" description="你的账号属于多个品牌空间。选择后，页面与数据会完整切换到该品牌。"><div className="workspace-list">{items?.map(item=><button key={item.tenantId} disabled={busy!==null} onClick={async()=>{setBusy(item.tenantId);try{onSelected(await postJson(`/api/v1/workspaces/${item.tenantId}/select`,{},authSessionSchema));}catch(reason){setError(reason instanceof Error?reason.message:"无法切换品牌空间。");setBusy(null);}}}><span className="workspace-icon"><Building2/></span><span><strong>{item.brandName}</strong><small>{item.role==="owner"?"品牌负责人":"只读成员"}</small></span><ArrowRight/></button>)}</div>{items===null?<p className="access-loading">正在读取品牌空间...</p>:null}</AccessFrame>}
export function NoPermissionPage({detail="当前账号尚未加入任何品牌空间。"}:{detail?:string}){return <AccessFrame eyebrow="访问受限" title="暂时没有可查看的品牌" description={detail}><div className="permission-state"><ShieldX/><p>请联系平台管理员核对邀请状态或品牌成员关系。</p></div></AccessFrame>}
