import { useState } from "react";
import { questionInsightSchema } from "../../contracts/product-read";
import { AlertTriangle, ArrowRight, CheckCircle2, CircleSlash2, ExternalLink, FileSearch, GitCompareArrows, Link2, Radar, ShieldCheck } from "lucide-react";
import { ErrorState, formatDate, labelOf, Loading, PageHeader, Status } from "./components/ProductUi";
import { useApi } from "./hooks/useApi";

type Nav={navigate:(to:string)=>void;initialQuestionId?:string};
const rootCauseLabel:Record<string,string>={sampling_insufficient:"样本不足",brand_truth_gap:"品牌事实缺口",product_service_gap:"产品或服务差距",website_structure_gap:"官网结构问题",content_coverage_gap:"内容覆盖不足",external_source_gap:"外部可信信源不足",reputation_risk:"口碑风险",model_volatility:"模型波动",competitor_reason_unclear:"竞品领先原因不明",no_action:"暂不行动"};

export function QuestionInsightsPage({navigate,initialQuestionId}:Nav){
  const [questionId,setQuestionId]=useState<string|null>(initialQuestionId??null);const[tab,setTab]=useState<"monitor"|"analyze"|"decide">("monitor");
  const endpoint=questionId?`/api/v1/question-insights?questionId=${encodeURIComponent(questionId)}`:"/api/v1/question-insights";
  const {data,error,retry}=useApi(endpoint,questionInsightSchema);
  const selected=data?.questions.find(item=>item.id===data.selectedQuestionId)??null;
  if(error)return <><PageHeader eyebrow="AI 监测" title="游客提问分析" description="从真实回答进入信源、竞争对手和优化方向。"/><ErrorState message={error} retry={retry}/></>;
  if(!data)return <Loading/>;
  return <><PageHeader eyebrow="AI 监测" title="游客提问分析" description="选择品牌关心的游客问题，核对多轮回答，再分析信源、竞争对手和可执行方向。"/>
    <section className="analysis-context" aria-label="分析口径">
      <div><span>问题组</span><strong>{data.context?`V${data.context.panelVersion}`:"尚无"}</strong></div><div><span>问题类型</span><strong>{selected?labelOf(selected.objectType):"尚未选择"}</strong></div>
      <div><span>AI 平台</span><strong>{data.context?.provider?labelOf(data.context.provider):"未记录"}</strong></div><div><span>采集方式</span><strong>{data.context?.surface?labelOf(data.context.surface):"未记录"}</strong></div>
      <div><span>模型 / 规则</span><strong>{data.context?.model??"未记录"}<small>{data.context?.rulesVersion??"规则未记录"}</small></strong></div><div><span>样本状态</span><strong>{data.context?`${data.context.effectiveSamples} 有效 · ${data.context.failedSamples} 失败`:"尚无样本"}<small>{data.context?.comparisonStatus==="single_platform"?"仅单平台，不做平台对比":data.context?.comparisonStatus==="comparable"?"口径可比较":"证据不足"}</small></strong></div>
    </section>
    <div className="workflow-tabs" role="tablist" aria-label="问题分析步骤"><button className={tab==="monitor"?"active":""} onClick={()=>setTab("monitor")}><span>1</span>监测问题</button><ArrowRight/><button className={tab==="analyze"?"active":""} onClick={()=>setTab("analyze")}><span>2</span>分析信源与竞对</button><ArrowRight/><button className={tab==="decide"?"active":""} onClick={()=>setTab("decide")}><span>3</span>决策优化方向</button></div>
    {tab==="monitor"?<div className="insight-monitor-grid"><section className="panel question-picker"><div className="compact-head"><div><h2>品牌关心的游客问题</h2><p>问题组版本不可覆盖；这里不是关键词库。</p></div><Status value={data.context?"approved":"pending"}/></div><div className="question-options">{data.questions.length?data.questions.map(item=><button key={item.id} className={item.id===data.selectedQuestionId?"selected":""} onClick={()=>setQuestionId(item.id)}><span className="question-copy"><strong>{item.text}</strong><small>{labelOf(item.objectType)} · {labelOf(item.journeyStage)}{item.audience?` · ${item.audience}`:""}</small></span><span className="question-counts"><b>{item.succeeded}</b> 有效 / {item.failed} 失败</span></button>):<div className="inline-empty">尚无已批准游客问题组。</div>}</div></section>
      <section className="panel"><div className="compact-head"><div><h2>{selected?.text??"尚未选择问题"}</h2><p>相同问题的各轮采集分别保留为独立证据。</p></div><Status value={data.answers.some(item=>item.status==="succeeded")?"completed":"pending"}/></div><div className="answer-rounds">{data.answers.length?data.answers.map((answer,index)=><article key={`${answer.round}-${index}`}><span className="round-badge">第 {answer.round} 轮</span><div><strong>{answer.status==="succeeded"?"回答已保存，可进入分析":answer.errorCode?`采集失败：${labelOf(answer.errorCode)}`:"尚未完成"}</strong><small>{answer.model} · {labelOf(answer.surface)} · {formatDate(answer.capturedAt)}</small><small>{answer.geoStatus==="completed"?"GEO 分析已完成":"GEO 分析尚无结果"} · {answer.citationCandidates} 个链接候选</small></div>{answer.id?<button className="text-action" onClick={()=>navigate(`/evidence/answers/${answer.id}`)}>查看原始回答 <ExternalLink/></button>:null}</article>):<div className="inline-empty">这个问题尚无采集记录。</div>}</div><div className="evidence-note"><ShieldCheck/><span>问题、问题组版本、平台、模型、轮次、时间与原始回答共同构成不可变证据。</span></div></section></div>:null}
    {tab==="analyze"?<div><div className="analysis-two-col"><section className="panel"><div className="compact-head"><div><h2>品牌与竞争对手</h2><p>只统计当前问题真实回答中已确认的实体。</p></div><Status value={data.entities.length?"completed":"pending"}/></div>{data.entities.length?<div className="table-scroll"><table><thead><tr><th>监测实体</th><th>角色</th><th>出现回答</th><th>明确提及</th><th>主张</th><th>适用排名</th></tr></thead><tbody>{data.entities.map(entity=><tr key={entity.id}><td><strong>{entity.name}</strong></td><td>{entity.role==="brand"?"本品牌":"竞争品牌"}</td><td>{entity.mentionedAnswers} / {data.context?.effectiveSamples??0}</td><td>{entity.certainMentions}</td><td>{entity.claimCount}</td><td>{entity.applicableRanks.length?entity.applicableRanks.join("、"):"不适用"}</td></tr>)}</tbody></table></div>:<div className="inline-empty">尚无获批准的竞争实体集，或该问题回答尚未完成 GEO 分析。这里不会补演示竞品。</div>}</section>
      <section className="panel"><div className="compact-head"><div><h2>回答使用了哪些信源</h2><p>链接候选、页面快照和明确引用分开显示。</p></div><Status value={data.sources.structuredCitations?"completed":"pending"}/></div><div className="source-facts"><div><GitCompareArrows/><span><strong>平台结构化引用</strong><small>{data.sources.structuredCitations?`${data.sources.structuredCitations} 条`:"当前回答未提供可验证结构化引用"}</small></span></div><div><Link2/><span><strong>回答正文与来源列表</strong><small>{data.sources.inlineLinks} 个正文链接 · {data.sources.sourceListItems} 个来源项，仅作为候选</small></span></div><div><FileSearch/><span><strong>来源页面快照</strong><small>{data.sources.successfulSnapshots} 个成功 · {Math.max(0,data.sources.snapshots-data.sources.successfulSnapshots)} 个失败或受阻</small></span></div><div><Radar/><span><strong>内容吸收候选</strong><small>{data.sources.absorptionCandidates} 条，仍需人工核对对应关系</small></span></div></div></section></div>
      <section className="panel evidence-boundary"><div className="compact-head"><div><h2>这一问题能够支持什么判断</h2><p>先分清观察事实、可比较范围与不能得出的结论。</p></div></div><div className="boundary-lines"><div><span>可以确认</span><p>每轮 AI 实际回答了什么，出现了哪些已确认实体和哪些可验证来源证据。</p></div><div><span>可以比较</span><p>只在问题、平台、入口、模型、区域和轮次口径一致时比较品牌与竞品。</p></div><div><span>暂不能确认</span><p>某个官网页面或某篇内容导致了品牌被提及、未提及或排名变化。</p></div><div><span>必须分开</span><p>中性品类问题、品牌直问、竞品直问和品牌对比问题不能混成一个提及率。</p></div></div></section></div>:null}
    {tab==="decide"?<div className="decision-layout"><section className="panel"><div className="compact-head"><div><h2>优化方向候选</h2><p>当前数据库只有品牌空间总体诊断；不会伪装成此问题专属结论。</p></div>{data.decision?<Status value={data.decision.evidenceStatus} tone={data.decision.evidenceStatus==="sufficient"?"good":"warn"}/>:<Status value="pending"/>}</div>{data.decision?<><div className="scope-warning"><AlertTriangle/><span><strong>适用范围：品牌空间最近一次总体诊断</strong><small>{data.decision.sampleCount} 个分析样本 · {data.decision.rulesVersion} · {data.decision.factLevel}</small></span></div><div className="diagnosis-summary"><span>主要判断</span><strong>{rootCauseLabel[data.decision.rootCause]??labelOf(data.decision.rootCause)}</strong><p>{data.decision.summary}</p></div><div className="action-list">{data.decision.actions.length?data.decision.actions.map(action=><article key={action.id}><div><span className="action-type">{labelOf(action.type)}</span><h3>{action.title}</h3><p>{action.rationale}</p></div><div className="action-meta"><Status value={action.priority} tone={action.priority==="high"?"warn":"neutral"}/><small>{action.factLevel} · {action.requiresApproval?"执行前需确认":"只读建议"}</small></div></article>):<div className="inline-empty">诊断没有形成动作候选，“暂不行动”也可能是正式结论。</div>}</div></>:<div className="inline-empty">尚无可核对诊断。下一步应补足样本或连接证据，而不是临时生成内容建议。</div>}</section>
      <aside className="panel decision-route"><div className="compact-head"><div><h2>决策路径</h2><p>不是品牌未被提到就立即写文章。</p></div></div>{["游客是否真的关心","品牌与竞品是否存在同口径差距","差距更可能来自哪里","内容是不是正确动作","批准、执行并按原口径复测"].map((label,index)=><div className="route-step" key={label}><span>{index+1}</span><div><strong>{label}</strong><small>{["问题必须来自已批准问题组。","样本不足或排名不适用时停止判断。","区分事实、业务、内容、官网、信源、口碑或模型波动。","业务缺口应改业务；证据不足应继续观察。","保存事实边界、权限、回执与复测口径。"][index]}</small></div></div>)}<div className="evidence-note"><CircleSlash2/><span>“不做内容、继续监测”是正式决策。</span></div></aside></div>:null}
  </>;
}
