import{createHash,randomUUID}from"node:crypto";import{z}from"zod";import{trustEvidenceBlueprintSchema,type TrustEvidenceBlueprint}from"../trust-evidence-blueprint/trust-evidence-blueprint.js";import type{SourceFetchResult}from"../citation-source/safe-source-fetcher.js";
export const trustSourceKeySchema=z.enum(["official_registry","licensed_platform","owned_site_filing","official_filing_registry"]);export type TrustSourceKey=z.infer<typeof trustSourceKeySchema>;
export const trustSourceTargetSchema=z.object({key:trustSourceKeySchema,label:z.string().min(1),url:z.string().url(),sourceRole:z.enum(["official_entry","licensed_platform","owned_site"])});
export const trustSourceResultSchema=z.object({id:z.string().uuid(),key:trustSourceKeySchema,label:z.string().min(1),url:z.string().url(),factLevel:z.literal("F1"),fetchStatus:z.enum(["succeeded","blocked","failed"]),verificationStatus:z.enum(["independently_verified","self_asserted","source_blocked","insufficient"]),httpStatus:z.number().int().nullable(),title:z.string().nullable(),textExcerpt:z.string().nullable(),contentSha256:z.string().regex(/^[a-f0-9]{64}$/).nullable(),errorCode:z.string().nullable(),capturedAt:z.string().datetime({offset:true}),verifiedSignals:z.array(z.string()),limitations:z.array(z.string().min(1))}).superRefine((x,c)=>{if(x.fetchStatus==="succeeded"&&!x.contentSha256)c.addIssue({code:"custom",message:"Successful source results require a content hash."});if(x.fetchStatus!=="succeeded"&&!x.errorCode)c.addIssue({code:"custom",message:"Unsuccessful source results require an error code."});});
export const trustSourceVerificationSchema=z.object({id:z.string().uuid(),tenantId:z.string().uuid(),rulesVersion:z.literal("trust-source-verification.v1"),blueprintId:z.string().uuid(),inputSha256:z.string().regex(/^[a-f0-9]{64}$/),status:z.literal("complete_with_gaps"),factLevel:z.literal("F2"),targetCount:z.literal(4),independentlyVerifiedCount:z.number().int().nonnegative(),selfAssertedCount:z.number().int().nonnegative(),blockedCount:z.number().int().nonnegative(),results:z.array(trustSourceResultSchema).length(4),resolvedEvidenceTasks:z.array(z.string()),remainingEvidenceTasks:z.array(z.string()),publicationAuthorized:z.literal(false),createdAt:z.string().datetime({offset:true})});
export type TrustSourceVerification=z.infer<typeof trustSourceVerificationSchema>;export type TrustSourceTarget=z.infer<typeof trustSourceTargetSchema>;
export const TRUST_SOURCE_TARGETS:TrustSourceTarget[]=[
 {key:"official_registry",label:"国家企业信用信息公示系统入口",url:"https://www.gsxt.gov.cn/index.html",sourceRole:"official_entry"},
 {key:"licensed_platform",label:"欣欣旅游旅行社认证页",url:"https://lxs.cncn.com/88893",sourceRole:"licensed_platform"},
 {key:"owned_site_filing",label:"北京珈程官网备案展示",url:"https://www.jiacheng666.com/",sourceRole:"owned_site"},
 {key:"official_filing_registry",label:"工信部 ICP 备案查询入口",url:"https://beian.miit.gov.cn/",sourceRole:"official_entry"},
].map(x=>trustSourceTargetSchema.parse(x));
const has=(text:string|null,re:RegExp)=>Boolean(text&&re.test(text));
function classify(target:TrustSourceTarget,capture:SourceFetchResult,capturedAt:string){const text=capture.textExcerpt;let verificationStatus:"independently_verified"|"self_asserted"|"source_blocked"|"insufficient"="insufficient",verifiedSignals:string[]=[],limitations:string[]=[];
 if(capture.status!=="succeeded"){verificationStatus="source_blocked";limitations=["本次只读访问未取得可保存正文，不能据此核验目标事实。","系统不会登录、提交验证码或绕过来源访问限制。"];}
 else if(target.key==="licensed_platform"){const company=has(text,/北京珈程国际旅行社有限公司/u),license=has(text,/L-BJ10127/u),scope=has(text,/国内旅游业务[\s\S]{0,80}入境旅游业务/u);verifiedSignals=[company?"页面展示公司全称":null,license?"页面展示许可证 L-BJ10127":null,scope?"页面展示国内旅游与入境旅游业务范围":null].filter((x):x is string=>Boolean(x));verificationStatus=company&&license&&scope?"independently_verified":"insufficient";limitations=["该快照证明欣欣平台在抓取时展示了这些信息，不等同于政府许可系统的实时查询结果。","页面中的商品、服务承诺和评价仍属于平台商家发布内容。"];}
 else if(target.key==="owned_site_filing"){const filing=/京ICP备2025121278号-1/u.exec(text??"")?.[0];verifiedSignals=filing?[`官网页脚展示 ${filing}`]:[];verificationStatus=filing?"self_asserted":"insufficient";limitations=["官网页脚属于品牌自有页面展示，不能独立证明备案主体与公司主体一致。","必须通过工信部官方查询结果或备案材料完成主体关联。"];}
 else {verificationStatus="insufficient";limitations=["入口页面本身不包含北京珈程的公司查询结果。","需取得带查询时间的官方结果页或原始材料后才能升级为独立核验。"];}
 return trustSourceResultSchema.parse({id:randomUUID(),key:target.key,label:target.label,url:target.url,factLevel:"F1",fetchStatus:capture.status,verificationStatus,httpStatus:capture.httpStatus,title:capture.title,textExcerpt:capture.textExcerpt,contentSha256:capture.contentSha256,errorCode:capture.errorCode,capturedAt,verifiedSignals,limitations});}
export function createTrustSourceVerification(tenantId:string,blueprint:TrustEvidenceBlueprint,captures:Record<TrustSourceKey,SourceFetchResult>,createdAt=new Date().toISOString()):TrustSourceVerification{const b=trustEvidenceBlueprintSchema.parse(blueprint);if(b.tenantId!==tenantId)throw new Error("Trust source verification tenant mismatch.");if(b.publicationAuthorized)throw new Error("Published blueprints are not accepted by this read-only verifier.");const results=TRUST_SOURCE_TARGETS.map(t=>classify(t,captures[t.key],createdAt));const platform=results.find(x=>x.key==="licensed_platform"),filing=results.find(x=>x.key==="official_filing_registry"),registry=results.find(x=>x.key==="official_registry");const resolvedEvidenceTasks=platform?.verificationStatus==="independently_verified"?["已保存欣欣认证页精确 URL 与独立页面快照"]:[];const remainingEvidenceTasks=[registry?.verificationStatus==="independently_verified"?null:"仍缺带查询时间的国家企业信用信息官方结果页或原始快照",filing?.verificationStatus==="independently_verified"?null:"仍缺工信部备案查询结果或可核验的域名主体关联材料"].filter((x):x is string=>Boolean(x));const inputSha256=createHash("sha256").update(JSON.stringify({blueprintId:b.id,blueprintHash:b.inputSha256,results:results.map(x=>({key:x.key,url:x.url,status:x.fetchStatus,verification:x.verificationStatus,http:x.httpStatus,error:x.errorCode,signals:x.verifiedSignals}))})).digest("hex");return trustSourceVerificationSchema.parse({id:randomUUID(),tenantId,rulesVersion:"trust-source-verification.v1",blueprintId:b.id,inputSha256,status:"complete_with_gaps",factLevel:"F2",targetCount:4,independentlyVerifiedCount:results.filter(x=>x.verificationStatus==="independently_verified").length,selfAssertedCount:results.filter(x=>x.verificationStatus==="self_asserted").length,blockedCount:results.filter(x=>x.verificationStatus==="source_blocked").length,results,resolvedEvidenceTasks,remainingEvidenceTasks,publicationAuthorized:false,createdAt});}
