import { randomUUID } from "node:crypto";
import pg from "pg";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { buildApp } from "../../src/app.js";
import { hashPassword } from "../../src/modules/identity/password.js";
import type { AppConfig } from "../../src/platform/config.js";
import { testDatabaseUrl,testRedisUrl } from "../support/environment.js";

const databaseUrl=testDatabaseUrl();const adminUrl=testDatabaseUrl("TEST_ADMIN_DATABASE_URL");const redisUrl=testRedisUrl();
describe.runIf(Boolean(databaseUrl&&adminUrl&&redisUrl))("invite identity and tenant isolation",()=>{const admin=new pg.Pool({connectionString:adminUrl});const tenantA=randomUUID();const tenantB=randomUUID();const userId=randomUUID();const multiId=randomUUID();const noMemberId=randomUUID();const origin="http://identity.test";const config:AppConfig={NODE_ENV:"test",HOST:"127.0.0.1",PORT:4274,DATABASE_URL:databaseUrl!,REDIS_URL:redisUrl!,LOG_LEVEL:"silent",PRODUCT_AUTH_MODE:"session"};
  beforeAll(async()=>{const passwordHash=await hashPassword("A-safe-test-password-2026");await admin.query(`insert into tenants(id,slug,display_name) values($1,$2,'身份品牌甲'),($3,$4,'身份品牌乙')`,[tenantA,`identity-${tenantA.slice(0,8)}`,tenantB,`identity-${tenantB.slice(0,8)}`]);await admin.query(`insert into platform_users(id,email,normalized_email,password_hash,status,created_at,updated_at) values($1,'owner@example.test','owner@example.test',$4,'active',now(),now()),($2,'multi@example.test','multi@example.test',$4,'active',now(),now()),($3,'none@example.test','none@example.test',$4,'active',now(),now())`,[userId,multiId,noMemberId,passwordHash]);await admin.query(`insert into tenant_memberships(user_id,tenant_id,role,status,created_at,updated_at) values($1,$3,'owner','active',now(),now()),($2,$3,'owner','active',now(),now()),($2,$4,'viewer','active',now(),now())`,[userId,multiId,tenantA,tenantB]);});
  afterAll(async()=>{await admin.end()});
  const login=async(app:ReturnType<typeof buildApp>,email:string,password="A-safe-test-password-2026")=>app.inject({method:"POST",url:"/api/v1/auth/login",headers:{host:"identity.test",origin,"content-type":"application/json"},payload:{email,password}});
  it("protects reads and uses a uniform invalid-login response",async()=>{const app=buildApp(config);try{const unauth=await app.inject({url:"/api/v1/workspace"});expect(unauth.statusCode).toBe(401);expect(unauth.headers["cache-control"]).toContain("no-store");const missing=await login(app,"missing@example.test","wrong");const wrong=await login(app,"owner@example.test","wrong");expect(missing.statusCode).toBe(401);expect(wrong.statusCode).toBe(401);expect(missing.json()).toEqual(wrong.json());expect(missing.body).not.toContain("missing@example.test");}finally{await app.close()}});
  it("logs a single-workspace member in, ignores tenant overrides, and revokes logout",async()=>{const app=buildApp(config);try{const response=await login(app,"OWNER@example.test");expect(response.statusCode).toBe(200);expect(response.json()).toMatchObject({selectedTenantId:tenantA,requiresWorkspaceSelection:false});const cookie=String(response.headers["set-cookie"]).split(";")[0]!;expect(response.headers["set-cookie"]).toContain("HttpOnly");expect(response.headers["set-cookie"]).toContain("SameSite=Lax");const workspace=await app.inject({url:`/api/v1/workspace?tenantId=${tenantB}`,headers:{cookie}});expect(workspace.statusCode).toBe(200);expect(workspace.json()).toMatchObject({tenantId:tenantA,brandName:"身份品牌甲"});expect(workspace.body).not.toContain(tenantB);const logout=await app.inject({method:"POST",url:"/api/v1/auth/logout",headers:{host:"identity.test",origin,cookie}});expect(logout.statusCode).toBe(204);expect((await app.inject({url:"/api/v1/workspace",headers:{cookie}})).statusCode).toBe(401);}finally{await app.close()}});
  it("requires explicit selection for multiple memberships and rotates the session",async()=>{const app=buildApp(config);try{const response=await login(app,"multi@example.test");expect(response.json()).toMatchObject({selectedTenantId:null,requiresWorkspaceSelection:true});const cookie=String(response.headers["set-cookie"]).split(";")[0]!;expect((await app.inject({url:"/api/v1/workspace",headers:{cookie}})).statusCode).toBe(409);const list=await app.inject({url:"/api/v1/workspaces",headers:{cookie}});expect(list.json().items).toHaveLength(2);const selected=await app.inject({method:"POST",url:`/api/v1/workspaces/${tenantB}/select`,headers:{host:"identity.test",origin,cookie}});expect(selected.statusCode).toBe(200);const rotated=String(selected.headers["set-cookie"]).split(";")[0]!;expect(rotated).not.toBe(cookie);expect((await app.inject({url:"/api/v1/workspace",headers:{cookie}})).statusCode).toBe(401);expect((await app.inject({url:"/api/v1/workspace",headers:{cookie:rotated}})).json()).toMatchObject({tenantId:tenantB,brandName:"身份品牌乙"});}finally{await app.close()}});
  it("returns forbidden for an authenticated account without membership",async()=>{const app=buildApp(config);try{const response=await login(app,"none@example.test");const cookie=String(response.headers["set-cookie"]).split(";")[0]!;expect((await app.inject({url:"/api/v1/workspaces",headers:{cookie}})).statusCode).toBe(403);expect((await app.inject({url:"/api/v1/workspace",headers:{cookie}})).statusCode).toBe(403);}finally{await app.close()}});
  it("lists membership names without requiring a preselected tenant context",async()=>{const app=buildApp(config);try{const response=await login(app,"multi@example.test");expect(response.statusCode).toBe(200);const cookie=String(response.headers["set-cookie"]).split(";")[0]!;const workspaces=await app.inject({url:"/api/v1/workspaces",headers:{cookie}});expect(workspaces.statusCode).toBe(200);expect(workspaces.json().items).toEqual(expect.arrayContaining([{tenantId:tenantA,brandName:"身份品牌甲",role:"owner"},{tenantId:tenantB,brandName:"身份品牌乙",role:"viewer"}]));}finally{await app.close()}});
});
