import{createHash,randomUUID}from"node:crypto";import{z}from"zod";import{optimizationActionPlanSchema,type OptimizationActionPlan}from"../optimization-action-plan/optimization-action-plan.js";
export const refundPolicyFieldSchema=z.object({key:z.enum(["scope_version","cancellation_windows","traveler_charges","incurred_costs","refund_timing","exceptions","responsibility_evidence"]),label:z.string().min(1),question:z.string().min(1),whyNeeded:z.string().min(1),requiredInputs:z.array(z.string().min(1)).min(1),acceptableEvidence:z.array(z.string().min(1)).min(1),visibility:z.enum(["internal_first","public_candidate"]),required:z.literal(true)});
export const refundPolicyPathSchema=z.object({key:z.enum(["current_policy","no_unified_policy"]),label:z.string().min(1),whenToChoose:z.string().min(1),nextStep:z.string().min(1),publicOutcome:z.string().min(1)});
export const refundPolicyIntakeSchema=z.object({id:z.string().uuid(),tenantId:z.string().uuid(),rulesVersion:z.literal("refund-policy-intake.v1"),actionPlanId:z.string().uuid(),actionPackageId:z.string().uuid(),inputSha256:z.string().regex(/^[a-f0-9]{64}$/),status:z.literal("waiting_facts"),factLevel:z.literal("F4"),sourceFindingCount:z.literal(7),fieldCount:z.literal(7),fields:z.array(refundPolicyFieldSchema).length(7),paths:z.array(refundPolicyPathSchema).length(2),completenessRules:z.array(z.string().min(1)).min(1),conflictRules:z.array(z.string().min(1)).min(1),missingInputs:z.array(z.string().min(1)).length(7),summaryDraftAuthorized:z.literal(false),publicationAuthorized:z.literal(false),createdAt:z.string().datetime({offset:true})});export type RefundPolicyIntake=z.infer<typeof refundPolicyIntakeSchema>;
const definitions=[
 {key:"scope_version",label:"适用产品与版本",question:"这套规则适用于哪些产品、出发日期和合同版本？",whyNeeded:"避免把某一产品条款误用于全部线路。",requiredInputs:["适用产品或订单类型","合同/规则版本号","生效日期与失效日期"],acceptableEvidence:["现行旅游合同","盖章或内部批准的政策文件"],visibility:"public_candidate"},
 {key:"cancellation_windows",label:"取消时间点",question:"游客在出发前不同时间取消时，分别适用什么处理规则？",whyNeeded:"游客最关心取消越晚是否损失越高。",requiredInputs:["时间节点的计算方式","每个时间节点的处理规则","出发当日与未出现规则"],acceptableEvidence:["合同解除条款","订单退订规则"],visibility:"public_candidate"},
 {key:"traveler_charges",label:"游客承担金额",question:"每个取消时间点，游客需要承担哪些明确金额或比例？",whyNeeded:"金额与比例属于高风险承诺，不能由 AI 推断。",requiredInputs:["固定金额或计算公式","比例的计算基数","币种与四舍五入规则"],acceptableEvidence:["合同费用条款","实际执行审批规则"],visibility:"internal_first"},
 {key:"incurred_costs",label:"已发生且不可退费用",question:"机票、酒店、门票、签证等已发生费用如何认定和提供凭证？",whyNeeded:"区分约定扣费与确已发生的第三方损失。",requiredInputs:["费用类别","认定时间点","凭证类型与提供方式"],acceptableEvidence:["供应商取消规则","付款或预订凭证","合同已发生费用条款"],visibility:"internal_first"},
 {key:"refund_timing",label:"退款办理时限",question:"退款从哪个节点开始计算，承诺多久完成，原路退回还是其他方式？",whyNeeded:"避免把审核时间、支付通道时间和到账时间混为一谈。",requiredInputs:["起算条件","内部办理时限","支付渠道预计到账时间","退款方式"],acceptableEvidence:["财务退款流程","合同退款条款"],visibility:"public_candidate"},
 {key:"exceptions",label:"例外与特殊情形",question:"不可抗力、景区关闭、证件问题、游客健康等情况如何处理？",whyNeeded:"例外不清会使公开规则与实际履约冲突。",requiredInputs:["例外情形清单","每类处理原则","需要的证明材料"],acceptableEvidence:["合同特别条款","应急与投诉处理制度"],visibility:"internal_first"},
 {key:"responsibility_evidence",label:"责任人与留痕",question:"谁批准退款、游客如何申请、需要保留哪些凭证？",whyNeeded:"让政策能够真实执行和追溯。",requiredInputs:["申请入口","审核责任角色","所需材料","结果通知与留痕方式"],acceptableEvidence:["内部流程文件","客服/财务岗位规则"],visibility:"internal_first"},
]as const;
export function createRefundPolicyIntake(tenantId:string,rawPlan:OptimizationActionPlan,createdAt=new Date().toISOString()):RefundPolicyIntake{const plan=optimizationActionPlanSchema.parse(rawPlan);if(plan.tenantId!==tenantId)throw new Error("Refund policy intake tenant mismatch.");const action=plan.packages.find(x=>x.key==="refund_policy");if(!action)throw new Error("Refund policy action package is missing.");if(action.status!=="waiting_facts")throw new Error("Refund policy action must be waiting for facts.");if(action.sourceFindingIds.length!==7)throw new Error(`Refund policy intake requires 7 source findings, found ${action.sourceFindingIds.length}.`);const fields=definitions.map(x=>refundPolicyFieldSchema.parse({...x,required:true}));const paths=[{key:"current_policy",label:"已有现行政策",whenToChoose:"已有正在使用的合同或退款规则。",nextStep:"提供原始条款后，AI 检查完整性、冲突和公开范围，再形成待审核摘要。",publicOutcome:"只有人工确认后，才可能形成公开候选。"},{key:"no_unified_policy",label:"目前没有统一政策",whenToChoose:"不同订单按合同或供应商实际损失处理，尚无统一版本。",nextStep:"保留证据缺口，建议仅说明以签署合同和实际发生费用为准。",publicOutcome:"系统不会虚构比例、金额或退款时限。"}].map(x=>refundPolicyPathSchema.parse(x));const completenessRules=["七个必填主题均需有事实值或明确标记不适用","每个金额、比例和时限必须关联依据材料与适用范围","合同版本、生效时间和适用产品缺一不可","公开候选与内部执行细节必须分层"];const conflictRules=["同一时间节点存在多个比例时必须阻断并要求确定适用版本","公开退款时限不得短于内部可执行流程","已发生费用不得写成无凭证的固定兜底扣费","例外条款不得覆盖或改写已确认的合同正文"];const inputSha256=createHash("sha256").update(JSON.stringify({planId:plan.id,actionPackageId:action.id,sourceFindingIds:[...action.sourceFindingIds].sort(),fields:fields.map(x=>x.key),rulesVersion:"refund-policy-intake.v1"})).digest("hex");return refundPolicyIntakeSchema.parse({id:randomUUID(),tenantId,rulesVersion:"refund-policy-intake.v1",actionPlanId:plan.id,actionPackageId:action.id,inputSha256,status:"waiting_facts",factLevel:"F4",sourceFindingCount:7,fieldCount:7,fields,paths,completenessRules,conflictRules,missingInputs:fields.map(x=>x.label),summaryDraftAuthorized:false,publicationAuthorized:false,createdAt});}
