import {describe,expect,it} from "vitest";import {DeepSeekAnswerClient} from "../../src/modules/observation/deepseek-answer-client.js";
const options={model:"deepseek-chat",temperature:0.2,maxTokens:1000,timeoutMs:30000};const context={language:"简体中文",regionContext:"中国大陆测试语境"};
const body=(content:string|null,finish="stop")=>({id:"answer-1",model:"deepseek-chat",choices:[{finish_reason:finish,message:{content}}],usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30}});
describe("DeepSeek answer client",()=>{
 it("captures a complete API answer without placing the key in evidence request",async()=>{const client=new DeepSeekAnswerClient({apiKey:"private-test-key",fetchImpl:(async()=>new Response(JSON.stringify(body("完整回答")),{status:200})) as typeof fetch});const result=await client.capture("问题",context,options);expect(result).toMatchObject({answerText:"完整回答",model:"deepseek-chat",totalTokens:30});expect(JSON.stringify(result.request)).not.toContain("private-test-key");});
 it("rejects a length-truncated response",async()=>{const client=new DeepSeekAnswerClient({apiKey:"test",fetchImpl:(async()=>new Response(JSON.stringify(body("未完成","length")),{status:200})) as typeof fetch});await expect(client.capture("问题",context,options)).rejects.toMatchObject({code:"incomplete_response",retryable:false});});
 it("rejects empty content and preserves the raw provider response",async()=>{const raw=body(null);const client=new DeepSeekAnswerClient({apiKey:"test",fetchImpl:(async()=>new Response(JSON.stringify(raw),{status:200})) as typeof fetch});try{await client.capture("问题",context,options);expect.unreachable();}catch(error){expect(error).toMatchObject({code:"empty_content",response:raw});}});
 it("classifies 429 as retryable and 400 as terminal",async()=>{for(const [status,retryable] of [[429,true],[400,false]] as const){const client=new DeepSeekAnswerClient({apiKey:"test",fetchImpl:(async()=>new Response(JSON.stringify({error:"x"}),{status})) as typeof fetch});await expect(client.capture("问题",context,options)).rejects.toMatchObject({code:`http_${status}`,retryable});}});
});
