import {createHash,randomUUID} from "node:crypto";import {z} from "zod";import {brandTruthCardSchema,type BrandTruthCard} from "../brand-truth/brand-truth.js";import {optimizationActionPlanSchema,type OptimizationActionPlan} from "../optimization-action-plan/optimization-action-plan.js";
export const trustEvidenceItemSchema=z.object({id:z.string().uuid(),factId:z.string().uuid(),statement:z.string().min(1),factLevel:z.literal("F1"),sourceReference:z.string().min(1),sourceClass:z.enum(["official_registry_reference","licensed_platform_reference","owned_site_snapshot"]),verificationState:z.enum(["user_confirmed_reference","independent_snapshot"]),sourceStrength:z.enum(["medium","high"]),publicUse:z.literal("allowed_with_attribution"),exactUrl:z.string().url().nullable(),missingEvidence:z.array(z.string().min(1))});
export const pageSectionSchema=z.object({key:z.enum(["legal_identity","travel_license","platform_presence","evidence_notes"]),heading:z.string().min(1),purpose:z.string().min(1),factIds:z.array(z.string().uuid()),requiredFields:z.array(z.string().min(1)).min(1),displayRules:z.array(z.string().min(1)).min(1)});
export const trustEvidenceBlueprintSchema=z.object({id:z.string().uuid(),tenantId:z.string().uuid(),rulesVersion:z.literal("trust-evidence-blueprint.v1"),brandTruthCardId:z.string().uuid(),brandTruthVersion:z.number().int().positive(),actionPlanId:z.string().uuid(),inputSha256:z.string().regex(/^[a-f0-9]{64}$/),status:z.literal("draft"),factLevel:z.literal("F4"),evidenceItemCount:z.number().int().positive(),evidenceItems:z.array(trustEvidenceItemSchema).min(1),pageSections:z.array(pageSectionSchema).length(4),machineReadableDraft:z.record(z.string(),z.unknown()),prohibitedClaims:z.array(z.string().min(1)).min(1),nextEvidenceTasks:z.array(z.string().min(1)),publicationAuthorized:z.literal(false),createdAt:z.string().datetime({offset:true})});
export type TrustEvidenceBlueprint=z.infer<typeof trustEvidenceBlueprintSchema>;
export type TrustEvidenceBlueprintInput={brandTruth:BrandTruthCard;actionPlan:OptimizationActionPlan;prohibitedClaims:string[]};
const wanted=[/工商登记名称/u,/成立日期/u,/注册资本/u,/企业类型/u,/经营状态/u,/旅行社业务经营许可证/u,/许可经营业务/u,/欣欣旅游平台存在资质认证/u,/独立抓取.*HTTP 200/u];
const classify=(reference:string)=>reference.includes("独立网页快照")?{sourceClass:"owned_site_snapshot" as const,verificationState:"independent_snapshot" as const,exactUrl:"https://www.jiacheng666.com/",missingEvidence:["当前证据未包含域名备案或域名主体关联材料"]}:reference.includes("欣欣")?{sourceClass:"licensed_platform_reference" as const,verificationState:"user_confirmed_reference" as const,exactUrl:null,missingEvidence:["缺少已保存的欣欣认证页精确 URL 与页面快照"]}:{sourceClass:"official_registry_reference" as const,verificationState:"user_confirmed_reference" as const,exactUrl:null,missingEvidence:["缺少已保存的官方查询精确入口、查询时间与原始页面快照"]};
export function createTrustEvidenceBlueprint(tenantId:string,input:TrustEvidenceBlueprintInput,createdAt=new Date().toISOString()):TrustEvidenceBlueprint{
 const truth=brandTruthCardSchema.parse(input.brandTruth),plan=optimizationActionPlanSchema.parse(input.actionPlan);if(truth.tenantId!==tenantId||plan.tenantId!==tenantId)throw new Error("Trust evidence input tenant mismatch.");if(truth.status!=="approved")throw new Error("Approved brand truth is required.");const action=plan.packages.find(x=>x.key==="license_evidence");if(!action||action.status!=="ai_can_prepare")throw new Error("License evidence action package is not ready for AI preparation.");
 const facts=truth.facts.filter(f=>f.status==="approved"&&f.public&&wanted.some(re=>re.test(f.statement)));if(facts.length!==wanted.length)throw new Error(`Trust evidence facts incomplete: expected ${wanted.length}, found ${facts.length}.`);
 const evidenceItems=facts.map(f=>{const c=classify(f.source.reference);return trustEvidenceItemSchema.parse({id:randomUUID(),factId:f.id,statement:f.statement,factLevel:"F1",sourceReference:f.source.reference,...c,sourceStrength:"medium",publicUse:"allowed_with_attribution"});});
 const ids=(re:RegExp)=>facts.filter(f=>re.test(f.statement)).map(f=>f.id);const pageSections=[
  {key:"legal_identity",heading:"企业身份",purpose:"用可核验字段明确品牌对应的工商主体。",factIds:ids(/工商登记名称|成立日期|注册资本|企业类型|经营状态/u),requiredFields:["公司全称","成立日期","注册资本","企业类型","经营状态","信息更新时间"],displayRules:["逐项显示来源名称和核验状态","不得用成立日期推导前身历史或行业经验"]},
  {key:"travel_license",heading:"旅行社经营许可",purpose:"让游客直接确认许可证编号和许可业务范围。",factIds:ids(/旅行社业务经营许可证|许可经营业务/u),requiredFields:["许可证编号","许可业务范围","来源","核验日期"],displayRules:["许可证不等于5A等级","许可含入境业务不等于已证明多语种服务能力"]},
  {key:"platform_presence",heading:"持牌平台与官网证据",purpose:"分别展示平台认证记录和品牌官网快照，不混同证据角色。",factIds:ids(/欣欣旅游平台存在资质认证|独立抓取.*HTTP 200/u),requiredFields:["平台或网站名称","精确链接","证据类型","快照时间","页面哈希"],displayRules:["品牌官网属于自有信源","平台记录只证明页面当时展示的认证状态"]},
  {key:"evidence_notes",heading:"证据说明",purpose:"向游客说明哪些已核验、哪些仍缺原始材料。",factIds:[],requiredFields:["事实更新时间","来源类别说明","未核验声明","纠错入口"],displayRules:["用户确认的来源引用不得标成独立网页核验","销量、满意度、榜单和团队规模不进入本区"]},
 ].map(x=>pageSectionSchema.parse(x));
 const machineReadableDraft={"@context":"https://schema.org","@type":"TravelAgency",name:truth.brandName,legalName:"北京珈程国际旅行社有限公司",foundingDate:"2024-12-06",url:"https://www.jiacheng666.com/",identifier:[{"@type":"PropertyValue",propertyID:"旅行社业务经营许可证",value:"L-BJ10127"}]};
 const prohibitedClaims=[...new Set(input.prohibitedClaims)].filter(Boolean);if(!prohibitedClaims.length)throw new Error("Prohibited claims are required.");const nextEvidenceTasks=[...new Set(evidenceItems.flatMap(x=>x.missingEvidence))];const inputSha256=createHash("sha256").update(JSON.stringify({truthId:truth.id,truthVersion:truth.version,planId:plan.id,facts:facts.map(f=>({id:f.id,statement:f.statement,source:f.source})),prohibitedClaims:[...prohibitedClaims].sort()})).digest("hex");
 return trustEvidenceBlueprintSchema.parse({id:randomUUID(),tenantId,rulesVersion:"trust-evidence-blueprint.v1",brandTruthCardId:truth.id,brandTruthVersion:truth.version,actionPlanId:plan.id,inputSha256,status:"draft",factLevel:"F4",evidenceItemCount:evidenceItems.length,evidenceItems,pageSections,machineReadableDraft,prohibitedClaims,nextEvidenceTasks,publicationAuthorized:false,createdAt});
}
